UniversityManagementSystemWebApp/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class IndexController : Controller
    {
        DepartmentManager departmentManager=new DepartmentManager();
        
        public ActionResult Index()
        {
            ViewBag.Departments=departmentManager.GetSelectListItemsForDropdown();
            return View();
        }
        [HttpGet]
        public ActionResult TimePicker()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TimePicker(Timepicker timepicker)
        {
            //timepicker.Time = TimeSpan.FromDays(1);
            return View();
        }
	}
}

UniversityManagementSystemWebApp/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>*@
@*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>*@

    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title DELL University</title>
        @Styles.Render("~/Content/css")
                @Scripts.Render("~/bundles/modernizr")
        <script src="~/Scripts/jquery-1.12.4.js"></script>
        <script src="~/Scripts/jquery.validate.js"></script>
        <link href="~/Content/bootstrap.css" rel="stylesheet"/>
        @*<link href="~/Content/Site.css" rel="stylesheet" />*@
        <link href="~/Content/themes/bootstrap-naz.css" rel="stylesheet" />
        <style>
            body {

                /*background-image: url(../../Content/image1.jpg);*/
                background-repeat: no-repeat;
                /*background-size: 100%;*/
                /*background-position: center;*/
                margin-left: 0px;
                /*margin: 50px;*/
            }
            #abc {
                /*margin-top: 80px;*/
            }
            /*.navbar-inverse {
                background: #111 !important;
                color: #FFF !important;
            }*/
             .navbar-custom {
                 background-color: #0026ff;
                 border-color: #e7e7e7;
             }

            .navbar-custom .navbar-brand {
                color: #ec971f;
            }

            .navbar-custom .navbar-brand:hover,
            .navbar-custom .navbar-brand:focus {
                color: #5e5e5e;
                background-color: transparent;
            }

            .navbar-custom .navbar-text {
                color: #777;
            }

            .navbar-custom .navbar-nav > li > a {
                color: #777;
            }

            .navbar-custom .navbar-nav > li > a:hover,
            .navbar-custom .navbar-nav > li > a:focus {
                color: #333;
                background-color: transparent;
            }

            .navbar-custom .navbar-nav > .active > a,
            .navbar-custom .navbar-nav > .active > a:hover,
            .navbar-custom .navbar-nav > .active > a:focus {
                color: #555;
                background-color: #0a31b1;
            }

            .navbar-custom .navbar-nav > .disabled > a,
            .navbar-custom .navbar-nav > .disabled > a:hover,
            .navbar-custom .navbar-nav > .disabled > a:focus {
                color: #ccc;
                background-color: transparent;
            }

            .navbar-custom .navbar-toggle {
                border-color: #ddd;
            }

            .navbar-custom .navbar-toggle:hover,
            .navbar-custom .navbar-toggle:focus {
                background-color: #ddd;
            }

            .navbar-custom .navbar-toggle .icon-bar {
                background-color: #0a31b1;
            }

            .navbar-custom .navbar-collapse,
            .navbar-custom .navbar-form {
                border-color: #0a31b1;
            }

            .navbar-custom .navbar-nav > .open > a,
            .navbar-custom .navbar-nav > .open > a:hover,
            .navbar-custom .navbar-nav > .open > a:focus {
                color: #555;
                background-color: #0a31b1;
            }

            

            .navbar-custom .navbar-link {
                color: #777;
            }

            .navbar-custom .navbar-link:hover {
                color: #333;
            }

            .navbar-custom .btn-link {
                color: #777;
            }

            .navbar-custom .btn-link:hover,
            .navbar-custom .btn-link:focus {
                color: #333;
            }

            .navbar-custom .btn-link[disabled]:hover,
            fieldset[disabled] .navbar-custom .btn-link:hover,
            .navbar-custom .btn-link[disabled]:focus,
            fieldset[disabled] .navbar-custom .btn-link:focus {
                color: #ccc;
            }
        </style>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active">@Html.ActionLink("Home", "Index", "Home") <span class="sr-only">(current)</span></li>


                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Department <span class="caret"></span></a>
                            <ul class="dropdown-menu ">
                                <li>@Html.ActionLink("Save Department", "Save", "Department")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("View All Departments", "ViewAll", "ViewAllDepartment")</li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Course <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Save Course", "Save", "Course")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("View Course Statics", "CourseView", "CourseAssign")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Unassign All Courses", "Unassign", "UnassignCourse")</li>

                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Teacher <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Save Teacher", "Save", "Teacher")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Assign Course To Teacher", "CourseAssign", "CourseAssign")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Student <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Register Student", "Save", "Student")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Enroll In a Course", "Enroll", "EnrollCourse")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Save Result", "Save", "StudentResult")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("View Result", "ViewResult", "ViewResult")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Class Room Allocation <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Allocate Classroom", "Save", "AllocateCllassroom")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("View Class Schedule", "ClassSchedule", "AllocateCllassroom")</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Unallocate All Classrooms", "Unassign", "UnallocateClassrooms")</li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    <div class="container body-content">

        @RenderBody()
        <hr id="abc"/>

        <footer>
            <p>&copy; <i>@DateTime.Now.Year Learn Hunter</i></p>
        </footer>
    </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        <script src="~/Scripts/jquery-1.12.4.min.js"></script>
        <script src="~/Scripts/jquery.validate.js"></script>
        <script src="~/Content/Scripts/bootstrap-hover-dropdown.min.js"></script>

        <script>
            $(function () {
                $("ul.nav li.dropdown").hover(function () {
                    $(".dropdown-menu", this).fadeIn("slow");
                }, function () {
                    $(".dropdown-menu", this).fadeOut("slow");
                });
            })
        </script>

        @RenderSection("scripts", required: false)
    </body>
</html>

UniversityManagementSystemWebApp/Views/Shared/_LayoutPage12.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @RenderSection("head", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .fa-1x {
            font-size: 1.5rem;
        }

        .navbar-toggler.toggler-example {
            cursor: pointer;
        }

        .dark-blue-text {
            color: #0A38F5;
        }

        .dark-pink-text {
            color: #AC003A;
        }

        .dark-amber-text {
            color: #ff6f00;
        }

        .dark-teal-text {
            color: #004d40;
        }
    </style>
</head>
<body class="fixed-sn light-blue-skin">
    <nav class="navbar navbar-light light-blue lighten-4">

        <!-- Navbar brand -->
        <a class="navbar-brand" href="#">Navbar</a>

        <!-- Collapse button -->
        <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1" aria-controls="navbarSupportedContent1"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="dark-blue-text"><i class="fa fa-bars fa-1x"></i></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
            </ul>
            <!-- Links -->

        </div>
        <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->
    <div>
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>

UniversityManagementSystemWebApp/Views/Shared/_MyLayout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Material Design Bootstrap Template</title>
    <!-- Font Awesome -->
    @RenderSection("head", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../Content/cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <!-- Bootstrap core CSS -->
    <link href="../../Content/mdbootstrap.com/previews/docs/latest/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="../../Content/mdbootstrap.com/previews/docs/latest/css/mdb.min.css" rel="stylesheet">
</head>
<body class="fixed-sn light-blue-skin">
    <!--Double navigation-->
    <header>
        <!-- Sidebar navigation -->
        <div id="slide-out" class="side-nav sn-bg-4 fixed">
            <ul class="custom-scrollbar">
                <!-- Logo -->
                <li>
                    <div class="logo-wrapper waves-light">
                        <a href="#"><img src="../../Content/mdbootstrap.com/img/logo/mdb-transparent.png" class="img-fluid flex-center"></a>
                    </div>
                </li>
                <!--/. Logo -->
                <!--Social-->
                <li>
                    <ul class="social">
                        <li><a href="#" class="icons-sm fb-ic"><i class="fa fa-facebook"> </i></a></li>
                        <li><a href="#" class="icons-sm pin-ic"><i class="fa fa-pinterest"> </i></a></li>
                        <li><a href="#" class="icons-sm gplus-ic"><i class="fa fa-google-plus"> </i></a></li>
                        <li><a href="#" class="icons-sm tw-ic"><i class="fa fa-twitter"> </i></a></li>
                    </ul>
                </li>
                <!--/Social-->
                <!--Search Form-->
                <li>
                    <form class="search-form" role="search">
                        <div class="form-group md-form mt-0 pt-1 waves-light">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                    </form>
                </li>
                <!--/.Search Form-->
                <!-- Side navigation links -->
                <li>
                    <ul class="collapsible collapsible-accordion">
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-chevron-right"></i> Submit blog<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href="#" class="waves-effect">Submit listing</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Registration form</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-hand-pointer-o"></i> Instruction<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href="#" class="waves-effect">For bloggers</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">For authors</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-eye"></i> About<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href="#" class="waves-effect">Introduction</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Monthly meetings</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a class="collapsible-header waves-effect arrow-r"><i class="fa fa-envelope-o"></i> Contact me<i class="fa fa-angle-down rotate-icon"></i></a>
                            <div class="collapsible-body">
                                <ul>
                                    <li>
                                        <a href="#" class="waves-effect">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Write a message</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Write a message</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Write a message</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="#" class="waves-effect">Write a message</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                <!--/. Side navigation links -->
            </ul>
            <div class="sidenav-bg mask-strong"></div>
        </div>
        <!--/. Sidebar navigation -->
        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-toggleable-md navbar-expand-lg scrolling-navbar double-nav">
            <!-- SideNav slide-out button -->
            <div class="float-left">
                <a href="#" data-activates="slide-out" class="button-collapse"><i class="fa fa-bars"></i></a>
            </div>
            <!-- Breadcrumb-->
            <div class="breadcrumb-dn mr-auto">
                <p>Material Design for Bootstrap</p>
            </div>
            <ul class="nav navbar-nav nav-flex-icons ml-auto">
                <li class="nav-item">
                    <a class="nav-link"><i class="fa fa-envelope"></i> <span class="clearfix d-none d-sm-inline-block">Contact</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"><i class="fa fa-comments-o"></i> <span class="clearfix d-none d-sm-inline-block">Support</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"><i class="fa fa-user"></i> <span class="clearfix d-none d-sm-inline-block">Account</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
        </nav>
        <!-- /.Navbar -->
    </header>
    <!--/.Double navigation-->
    <!--Main Layout-->
<main>
    <div class="container body-content">


        @RenderBody()

        <hr />

        <footer>
            <p>&copy; <i>@DateTime.Now.Year - All right Reserved Void Group BITM</i></p>
        </footer>
    </div>
</main>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!--Main Layout-->
    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="../../Content/mdbootstrap.com/previews/docs/latest/js/jquery-3.3.1.min.js"></script>
    <!-- Tooltips -->
    <script type="text/javascript" src="../../Content/mdbootstrap.com/previews/docs/latest/js/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="../../Content/mdbootstrap.com/previews/docs/latest/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="../../Content/mdbootstrap.com/previews/docs/latest/js/mdb.min.js"></script>
    <script>

        // SideNav Initialization
        $(".button-collapse").sideNav();

    </script>
</body>
<!-- Mirrored from mdbootstrap.com/previews/docs/latest/html/navigation/side-nav-fixed-navbar-fixed.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 07 Sep 2018 16:53:33 GMT -->
</html>