UniversityManagementSystemWebApp/Models/ClassSchedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemWebApp.Models
{
    public class ClassSchedule
    {
        public int CourseId { get; set; }
        [Required]
        [Display (Name = "Department")]
        public int DepartmentId { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string Schedule { get; set; }
    }
}

UniversityManagementSystemWebApp/Controllers/AllocateCllassroomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemWebApp.Manager;
using UniversityManagementSystemWebApp.Models;
using UniversityManagementSystemWebApp.Models.View_Model;

namespace UniversityManagementSystemWebApp.Controllers
{
    public class AllocateCllassroomController : Controller
    {
        private DepartmentManager departmentManager;
        private CourseManager courseManager;
        private RoomManager roomManager;
        private DayManager dayManager;
        private AllocateClassroomsManager allocateClassroomsManager;

        public AllocateCllassroomController()
        {
            departmentManager=new DepartmentManager();
            courseManager=new CourseManager();
            roomManager=new RoomManager();
            dayManager=new DayManager();
            allocateClassroomsManager=new AllocateClassroomsManager();
        }
        //
        // GET: /AllocateCllassroom/
        [HttpGet]
        public ActionResult Save()
        {
            ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
            ViewBag.Rooms = roomManager.GetAllRoomCodeList();
            ViewBag.Days = dayManager.GetAllDayList();
            return View();
        }
        [HttpPost]

        public ActionResult Save(AllocateClassrooms allocateClassrooms)
        {
            //if (ModelState.IsValid)
            //{
                string message = allocateClassroomsManager.Save(allocateClassrooms);
                ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
                ViewBag.Rooms = roomManager.GetAllRoomCodeList();
                ViewBag.Days = dayManager.GetAllDayList();
                ViewBag.Message = message;
                ModelState.Clear();
                return View();
            //}
            //else
            //{
            //    ViewBag.Message = "Model is not valid";
            //    return View();
            //}
        }
        public JsonResult GetCourseByDepartmentId(int departmentId)
        {
            List<Course> courseList = courseManager.GetCoursesById(departmentId);
            return Json(courseList);
        }




        //--------------Class Schedule--------------------

        [HttpGet]
        public ActionResult ClassSchedule()
        {
            ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
            return View();
        }

        [HttpPost]
        public ActionResult ClassSchedule(ClassSchedule classSchedule)
        {
            ViewBag.Departments = departmentManager.GetSelectListItemsForDropdown();
            return View();
        }

        public JsonResult GetClassScheduleByDepartmentId(int departmentId)
        {
            List<Course> courses=courseManager.GetCoursesById(departmentId);             
            List<ScheduleViewMode> schedules=new List<ScheduleViewMode>();
            foreach (var course in courses)
            {
                string scheduleView = allocateClassroomsManager.GetAllSchedule(departmentId);
                if (scheduleView == "")
                {
                    scheduleView = "Not Scheduled Yet";
                }
                ScheduleViewMode scheduleViewMode=new ScheduleViewMode();
                scheduleViewMode.CourseCode = course.Code;
                scheduleViewMode.CourseName = course.Name;
                scheduleViewMode.Schedule = scheduleView;
                schedules.Add(scheduleViewMode);
            }
            return Json(schedules);
        }
       
	}
}

UniversityManagementSystemWebApp/Views/AllocateCllassroom/ClassSchedule.cshtml
@model UniversityManagementSystemWebApp.Models.ClassSchedule
@{
    ViewBag.Title = "Class Schedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #wrapper {
        width: 50%;
        margin: 0 auto;
    }

    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    th {
        background-color: #4CAF50;
        color: white;
    }
</style>



<div id="wrapper">
    <hr/>
    <h3>Class Schedule</h3>
    <hr/>
    @using (Html.BeginForm(null, null, FormMethod.Post))
    {
         <div class="form-group">
            @Html.LabelFor(x => x.DepartmentId, new {@class = "col-md-3 control-label"})
            @Html.DropDownListFor(x => x.DepartmentId, new SelectList(ViewBag.Departments, "Value", "Text"), new {@class = "form-control"})
            @Html.ValidationMessageFor(x => x.DepartmentId)
        </div>
        <table border="1">
            <thead>
            <tr>
                <th>Course Code</th>
                <th>Name</th>
                <th>Schedule Info</th>
            </tr>
            </thead>
            <tbody id="ScheduleInfo"></tbody>
        </table>
    }
</div>
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script>
    $(document).ready(function() {
        $("#DepartmentId").change(function () {
            $("#ScheduleInfo").empty();
            var deptId = $("#DepartmentId").val();
            var json =
            {
                departmentId: deptId
            };
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetClassScheduleByDepartmentId", "AllocateCllassroom")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $.each(data, function (key, value) {
                        $("#ScheduleInfo").append('<tr> <td>' + value.CourseCode + '</td> <td>' + value.CourseName + '</td> <td>' + value.Schedule + '</td></tr>');
                    });
                }
            });
        });
    });
</script>

UniversityManagementSystemWebApp/Views/AllocateCllassroom/Save.cshtml
@model UniversityManagementSystemWebApp.Models.AllocateClassrooms
@{
    ViewBag.Title = "Allocate Classrooms";
    //Layout = "~/Views/Shared/_MyLayout1.cshtml";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .field-validation-error {
        margin-left: 180px;
        color: red;
    }

    #wrapper {
        width: 60%;
        margin: 0 auto;
    }

    input {
        width: 240px;
    }
</style>
<link href="~/Content/mdtimepicker.css" rel="stylesheet" />
<div id="wrapper">
    <hr />
    <h3>Allocate Classrooms</h3>
    <hr />
    @using (Html.BeginForm(null, null, FormMethod.Post, new { Id = "Allocate" }))
    {
        <div class="form-group">
            @Html.LabelFor(x => x.DepartmentId, new { @class = "col-md-3 control-label" })
            @Html.DropDownListFor(x => x.DepartmentId, new SelectList(ViewBag.Departments, "Value", "Text"), new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.DepartmentId)
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.CourseId, new { @class = "col-md-3 control-label" })
            <select id="CourseId" name="CourseId" class="form-control">
                <option value="">--Select--</option>
            </select>
            @Html.ValidationMessageFor(x => x.CourseId)
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.RoomId, new { @class = "col-md-3 control-label" })
            @Html.DropDownListFor(x => x.RoomId, new SelectList(ViewBag.Rooms, "Value", "Text"), new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.RoomId)
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.DayId, new { @class = "col-md-3 control-label" })
            @Html.DropDownListFor(x => x.DayId, new SelectList(ViewBag.Days, "Value", "Text"), new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.DayId)
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.FromTime, new { @class = "col-md-3 control-label" })
            @Html.TextBoxFor(x => x.FromTime, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.FromTime)
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.ToTime, new { @class = "col-md-3 control-label" })
            @Html.TextBoxFor(x => x.ToTime, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.ToTime)
        </div>
        <div class="col-md-offset-3 col-md-9">
            <input type="submit" value="Allocate" class="btn btn-success" />
        </div>
    }
    @if (ViewBag.Message != null)
    {
        <h3>@ViewBag.Message</h3>
    }
</div>
@section Scripts {
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/mdtimepicker.js"></script>
    <script src="~/Scripts/jquery.datetimepicker.js"></script>
    <script>
        $(document).ready(function () {
            $('#FromTime').mdtimepicker();
            $('#ToTime').mdtimepicker();

            $("#Allocate").validate({
                rules: {
                    CourseId: "required"
                },
                messages: {
                    CourseId: "Please select the Course Name!"
                }
            });
            $("#DepartmentId").change(function () {
                $("#CourseId").empty();
                var deptId = $("#DepartmentId").val();
                var json =
                {
                    departmentId: deptId
                };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseByDepartmentId", "AllocateCllassroom")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        $("#CourseId").append('<option value="">--Select---</option');
                        $.each(data, function (key, value) {
                            $("#CourseId").append('<option value=' + value.Id + '>' + value.Name + '</option>');
                        });
                    }
                });
            });


        });
    </script>
}